ROWS = 15
COLS = 15
TILE_SIZE = 48
SIDE_PANEL = 300
SCREEN_WIDTH = TILE_SIZE * COLS
SCREEN_HEIGHT = TILE_SIZE * ROWS
FPS = 60
health = 100
money = 720
TOTAL_LEVELS = 7

#enemy constant
SPAWN_COOLDOWN = 380

#turret constants
TURRET_LEVELS = 4
BUY_COST = 185
UPGRADE_COST = 125
KILL_REWARD = 5
LEVEL_COMPLETE_REWARD = 50
ANIMATION_STEPS = 8
ANIMATION_DELAY = 15
DAMAGE = 7